name: C/C++ CI

on:
  push:
    branches: [ "master", "r" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    name: Build and test on the latest Ubuntu

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure --disable-openssl --enable-gettext --enable-debug=-O0

    - name: make
      run: make

    - name: make test-lib print-info
      run: make test-lib print-info

    - name: make test-full
      run: make test-full


  build-powerpc64:
    runs-on: ubuntu-latest
    name: Build and test on PowerPC 64
    needs: build-ubuntu

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get install -y qemu-user-static binfmt-support \
          gcc-powerpc64-linux-gnu libc-dev-ppc64-cross

    - name: configure
      run: |
        ./configure --disable-openssl --disable-gettext --enable-static \
          --cc=powerpc64-linux-gnu-gcc

    - name: make
      run: make

    - name: make test-lib print-info
      run: make test-lib print-info

    - name: make test-full
      run: make test-full


  build-windows:
    runs-on: windows-latest
    name: Build and test on Windows
    needs: build-ubuntu

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild (VS 2022)
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Build solution (Release x64)
      run: msbuild build\vc-2010\rhash.vcxproj /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143

    - name: Run tests
      run: bash.exe tests/test_rhash.sh build/vc-2010/Release-x64/rhash.exe

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          build/vc-2010/Release-x64/**
          !**/*.pdb
